Add chrome$webRequest
Shraymonks/flow-interfaces-chrome pull request #15
Opened 2018-04-24 07:37 UTC by briancollins

This adds type definitions for the `webRequest` API. I went through the documentation manually, so there could be some mistakes, but it is working correctly for the project that I am working on.

2018-04-24 07:42 UTC, briancollins commented
Thanks for the great library, by the way!

2018-05-01 00:59 UTC, Shraymonks requested changes
Thanks for adding this!

2018-05-01 00:59 UTC, Shraymonks commented on interfaces/webRequest.js
> +type chrome$HttpHeaders = Array<{name: string, value?: any, binaryValue?: any}>;
Based on https://developer.chrome.com/extensions/webRequest#type-HttpHeaders

Sounds like this should be something like:
```
Array<{name: string, value: any} | {name:string, binaryValue: any}>
```

2018-05-01 00:59 UTC, Shraymonks commented on interfaces/webRequest.js
> +  bytes?: any,
`ArrayBuffer` instead of `any`?

2018-05-01 00:59 UTC, Shraymonks commented on interfaces/webRequest.js
> +type chrome$FormDataItem = any;
`ArrayBuffer | string`?

2018-05-01 00:59 UTC, Shraymonks commented on package.json
> +  "version": "0.5.0"
Remove this, I'll bump the version afterwards.

2018-05-01 13:55 UTC, briancollins commented
Thanks for the review!

2018-05-07 18:28 UTC, Shraymonks approved these changes

2018-05-07 18:29 UTC, merged

2018-07-12 08:37 UTC, ssorallen commented
This introduced an error in v0.5.0:

    Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/flow-interfaces-chrome/interfaces/webRequest.js:241:29

    Cannot resolve name chrome$OnErrorOccurredOptions.

        238│         error: string,
        239│       }) => ?chrome$BlockingResponse,
        240│       filter?: chrome$RequestFilter,
        241│       extraInfoSpec?: Array<chrome$OnErrorOccurredOptions>,
        242│     ): void,
        243│   },
        244│ };

I will open an issue and send a PR.