Add annotations for `chrome.notifications`
Shraymonks/flow-interfaces-chrome pull request #2
Opened 2017-01-18 07:28 UTC by ssorallen

[chrome.notifications][1]

* `chrome.notifications.create` has a signature best described using
  unions for each of its parameters rather than a union of multiple
  full function signatures.

[1]: https://developer.chrome.com/apps/notifications

2017-01-18 07:32 UTC, ssorallen commented
Flow currently does not support [function overloading in object types](https://github.com/facebook/flow/issues/1556), so `chrome.create` cannot easily be written with its 3 possible signatures. While the version in this PR is not perfectly correct (it would be valid to call it with `create(chrome$NotificationOptions, chrome$NotificationOptions)`, for example), the version here is helpful.

2017-01-18 18:20 UTC, Shraymonks requested changes
Thanks for the PR!

I think the real issue here is that flow doesn't currently support non-trailing optional parameters.

2017-01-18 18:20 UTC, Shraymonks commented on interfaces/notifications.js
> +  create(
You can do something like this instead as a workaround:
```
create: (
  ((
    notificationId: string,
    options: chrome$NotificationOptions,
    callback?: (notificationId: string) => void
  ) => void) &
  ((
    options: chrome$NotificationOptions,
    callback?: (notificationId: string) => void
  ) => void)
),
```

2017-01-20 05:06 UTC, ssorallen commented
@Shraymonks I added your suggested change. It works fine. Let me know what you think.

2017-01-20 05:14 UTC, Shraymonks approved these changes

2017-01-20 05:14 UTC, merged

2017-01-20 05:14 UTC, Shraymonks commented
Thanks!

2017-01-26 04:36 UTC, ssorallen commented
@Shraymonks Could you release a version of the NPM package with this PR in it? I am using this package in a project and needed the notification types!

2017-01-26 16:57 UTC, Shraymonks commented
@ssorallen Done!