Added contentSettings interface
Shraymonks/flow-interfaces-chrome pull request #27
Opened 2019-03-12 18:19 UTC by avartanii

I added the contentSettings interface as it was preventing me from committing what I wanted on a project. Please let me know if it needs any modification.

2019-03-12 18:38 UTC, Shraymonks requested changes
Thanks for adding this!

2019-03-12 18:38 UTC, Shraymonks commented on interfaces/contentSettings.js
> +    scope: chrome$Scope,
`scope` is optional
```suggestion
    scope?: chrome$Scope,
```

2019-03-12 18:38 UTC, Shraymonks commented on interfaces/contentSettings.js
> +  }, callback: () => void): void,
`callback` is optional here
```suggestion
  }, callback?: () => void): void,
```

2019-03-12 18:38 UTC, Shraymonks commented on interfaces/contentSettings.js
> +  }, callback: (details: { setting: * }) => void): void,
use `any` instead of `*` here
```suggestion
  }, callback: (details: { setting: any }) => void): void,
```

2019-03-12 18:38 UTC, Shraymonks commented on interfaces/contentSettings.js
> +    setting: *,
use `any` instead of `*` here
```suggestion
    setting: any,
```

2019-03-12 18:38 UTC, Shraymonks commented on interfaces/contentSettings.js
> +  }, callback: () => void): void,
`callback` is optional here
```suggestion
  }, callback?: () => void): void,
```

2019-03-12 18:38 UTC, Shraymonks commented on interfaces/contentSettings.js
> +  getResourceIdentifiers(callback?: (resourceIdentifiers?: Array<chrome$ResourceIdentifier>) => void): void,
`callback` isn't optional here
```suggestion
  getResourceIdentifiers(callback: (resourceIdentifiers?: Array<chrome$ResourceIdentifier>) => void): void,
```

2019-03-12 18:38 UTC, Shraymonks commented on interfaces/contentSettings.js
> +  description: string,
`description` is optional
```suggestion
  description?: string,
```

2019-03-12 20:08 UTC, avartanii commented
Addressed requested changes in new commit. Thanks for the feedback! This is my first open source contribution and I'm new to flow so thanks for taking the time to review.

2019-03-13 14:36 UTC, avartanii commented
Any chance you could merge this today? It's kinda blocking me at work =)

2019-03-13 18:41 UTC, Shraymonks approved these changes

2019-03-13 18:41 UTC, merged