Add `extension` and `extenstionType`
Shraymonks/flow-interfaces-chrome pull request #3
Opened 2017-01-27 16:33 UTC by ssorallen

* Add the type for [`chrome.extension`][1]
* Expose `chrome.extensionType`, which already existed, on the `chrome` object

[1]: https://developer.chrome.com/extensions/extension

2017-01-28 09:10 UTC, Shraymonks requested changes
@ssorallen Nice!

2017-01-28 09:10 UTC, Shraymonks commented on interfaces/extension.js
> +  lastError: ?{message: string},
Based on https://developer.chrome.com/extensions/extension#property-lastError, seems like this should technically be `lastError: {message: string} | void,`

2017-01-28 09:10 UTC, Shraymonks commented on interfaces/extension.js
> +  getBackgroundPage(): ?any,
Just do `: any`

2017-01-28 16:42 UTC, ssorallen commented
@Shraymonks Thanks for the review. I added both of your suggestions.

2017-01-29 07:28 UTC, Shraymonks approved these changes

2017-01-29 07:28 UTC, merged

2017-01-29 07:28 UTC, Shraymonks commented
Thanks!